name: dnd_301_final
description: A DnD Game State Manager

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  google_sign_in:
  image_picker:
  async: '>=1.13.3 <3.0.0'
  protobuf: ^0.10.2
  http: ^0.11.3+16
  http2: ^0.1.7
  grpc: ^0.6.5
  qr_flutter: '^1.1.1'
  qr_reader: "^0.1.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
#  flutter_launcher_icons:
#
## Select app icon
#flutter_icons:
#  image_path: "assets/dadlogo2.png"
#  android: true
#  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/alucard.jpg
    - assets/dadlogo2.png
    - assets/monster_images/beholder.jpg
    - assets/monster_images/dragon.png
    - assets/monster_images/fire_giant.jpg
    - assets/placeholder.jpg
    - assets/monster_images/yuan-ti.jpg
    - assets/character_images/archer.jpg
    - assets/character_images/knight.jpg
    - assets/character_images/mage.jpg
    # Race images
    - assets/race_images/Aarakocra.png
    - assets/race_images/Aasimar.png
    - assets/race_images/Bugbear.png
    - assets/race_images/Centaur.png
    - assets/race_images/Dragonborn.png
    - assets/race_images/Dwarf.png
    - assets/race_images/Elf.png
    - assets/race_images/Feral Tiefling.png
    - assets/race_images/Firbolg.png
    - assets/race_images/Genasi.png
    - assets/race_images/Gith.png
    - assets/race_images/Gnome.png
    - assets/race_images/Goblin.png
    - assets/race_images/Goliath.png
    - assets/race_images/Half-Elf.png
    - assets/race_images/Half-Orc.png
    - assets/race_images/Halfling.png
    - assets/race_images/Hobgoblin.png
    - assets/race_images/Human.png
    - assets/race_images/Kenku.png
    - assets/race_images/Kobold.png
    - assets/race_images/Lizardfolk.png
    - assets/race_images/Minotaur.png
    - assets/race_images/Orc.png
    - assets/race_images/Tabaxi.png
    - assets/race_images/Tiefling.png
    - assets/race_images/Tortle.png
    - assets/race_images/Triton.png
    - assets/race_images/Yuan-ti Pureblood.png
    #classes
    - assets/class_images/Barbarian.png
    - assets/class_images/Bard.png
    - assets/class_images/Cleric.png
    - assets/class_images/Druid.png
    - assets/class_images/Fighter.png
    - assets/class_images/Monk.png
    - assets/class_images/Paladin.png
    - assets/class_images/Ranger.png
    - assets/class_images/Rogue.png
    - assets/class_images/Sorcerer.png
    - assets/class_images/Warlock.png
    - assets/class_images/Wizard.png
    #stats icons
    - assets/icon_assets/Charisma.png
    - assets/icon_assets/Constitution.png
    - assets/icon_assets/Dexterity.png
    - assets/icon_assets/Intelligence.png
    - assets/icon_assets/Strength.png
    - assets/icon_assets/Wisdom.png
    #dm icon
    - assets/icon_assets/dm_icon.png
    #gender icons
    - assets/icon_assets/male.png
    - assets/icon_assets/female.png
    #class icons
    - assets/class_images/icons/barbarian-icon.png
    - assets/class_images/icons/bard-icon.png
    - assets/class_images/icons/cleric-icon.png
    - assets/class_images/icons/druid-icon.png
    - assets/class_images/icons/fighter-icon.png
    - assets/class_images/icons/monk-icon.png
    - assets/class_images/icons/paladin-icon.png
    - assets/class_images/icons/ranger-icon.png
    - assets/class_images/icons/rogue-icon.png
    - assets/class_images/icons/sorcerer-icon.png
    - assets/class_images/icons/warlock-icon.png
    - assets/class_images/icons/wizard-icon.png

    #monster list file
    - assets/dad_5e_monster_manual.txt

    #shield (ac) - sword - armor icons
    - assets/shield.png
    - assets/sword.png
    - assets/armor.png


  fonts:
        - family: Nunito
          fonts:
            - asset: assets/Nunito.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages